pipeline:
    name: rails
    identifier: rails
    allowStageExecutions: false
    projectIdentifier: Ruby
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: org.Github
                repoName: harnessrails
                build: <+input>
    stages:
        - stage:
              name: CI
              identifier: CI
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: org.GKE
                          namespace: harness-builds
                  serviceDependencies:
                      - identifier: PostGres
                        name: PostGres
                        type: Service
                        spec:
                            connectorRef: org.Dockerhub
                            image: postgres:11-alpine
                            privileged: false
                            envVariables:
                                POSTGRES_USER: postgres
                                POSTGRES_PASSWORD: postgres
                            args:
                                - --health-cmd pg_isready
                                - --health-interval 10s
                                - --health-timeout 5s
                                - --health-retries 5s
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Linting
                                identifier: Linting
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: pipelinecomponents/rubocop:latest
                                    shell: Sh
                                    command: rubocop --format junit --out report.xml || true
                                    reports:
                                        type: JUnit
                                        spec:
                                            paths:
                                                - report.xml
                                failureStrategies: []
                          - step:
                                type: Run
                                name: Setup DB
                                identifier: Setup_DB
                                spec:
                                    connectorRef: org.Dockerhub
                                    image: ruby:3.1.0
                                    shell: Sh
                                    command: |
                                        bundle install --jobs 4 --retry 3
                                        ls
                                        bundle exec rails db:create
                                    envVariables:
                                        RAILS_ENV: test
                                        POSTGRES_USER: postgres
                                        POSTGRES_PASSWORD: postgres
                                        DATABASE_URL: postgres://postgres:@localhost:5432/test
